#ifndef M_ERROR_CODES_H_
#define M_ERROR_CODES_H_

#define NO_ERROR						0
#define ERR_NULL_PTR					1
#define ERR_BAD_ARGS					2
#define ERR_SGTL5000_WRITE_FAIL 		3

#define ERR_ALLOC_FAIL					5

#define ERR_PIPELINE_NULL				4
#define ERR_PIPELINE_FULL				6
#define ERR_POSITION_ILLEGAL			7
#define ERR_POSITION_OCCUPIED			8

#define ERR_TRANSFORMER_MALFORMED		9
#define ERR_ARRAY_MALFORMED				10

#define ERR_POT_LINK_MALFORMED			11
#define ERR_SWITCH_LINK_MALFORMED		12

#define ERR_MUTEX_UNAVAILABLE			13

#define ERR_FIXED_ARRAY_FULL			14

#define ERR_BUSTED_MSG					15
#define ERR_BAD_REQUEST					16

#define ERR_QUEUE_SEND_FAILED			17
#define ERR_QUEUE_FULL					18
#define ERR_LOOP_DETECTED				19

#define ERR_NODE_PRIVATE				20
#define ERR_PIPELINE_BUSTED				21

#define ERR_INVALID_MESSAGE				22

#define ERR_VALUE_OUT_OF_BOUNDS			23

#define ERR_INVALID_PARAMETER_ID		24
#define ERR_INVALID_SETTING_ID			25
#define ERR_INVALID_TRANSFORMER_ID		26
#define ERR_INVALID_PROFILE_ID			27

#define ERR_INCONSISTENT_BACK_PIPELINE	28

#define ERR_SPI_INIT_FAIL				29
#define ERR_SD_INIT_FAIL				30
#define ERR_SD_MOUNT_FAIL				31
#define ERR_FOPEN_FAIL					32
#define ERR_UNFINISHED_WRITE			33
#define ERR_MANGLED_FILE				34

#define ERR_I2C_FAIL					35
#define ERR_NO_RESPONSE					36
#define ERR_COMMS_FAIL					37

#define ERR_SPI_FAIL					38
#define ERR_CURRENTLY_EXHAUSTED			39

#define ERR_UNKNOWN_ERR					4999
#define ERR_UNIMPLEMENTED				5000

const char *m_error_code_to_string(int error_code);

#endif
